### PR TITLE
Add search bar

### PR DESCRIPTION
**Pull request by nickrwann**
Added Search Bar + Search Bar CSS
- Changed formatting of member first name, last name, class year, and current city to snake case in order to perform search functionality
- Added search functionality to member model for routing
- Added javascript to index html to adjust UI/UX depending on search criteria
- Added search functionality specifically for member first & last name

### CODE REVIEW

**Review by Alexn0910 — COMMENTED** [review]
Code review: Looks good, but fix conflicts with Master.

**Review by Alexn0910 — COMMENTED** [review]
Code Review: Conflicts fixed.

**Comment by nickrwann** [comment]
> Code Review: Conflicts fixed.

Conflicts were fixed. Issue resided within conflicting snake & camel case variables which were not merged properly. Adjusted merge changes so ensure that alumni first & last name were accepted within the model as snake case.

**Comment by nickrwann** [comment]
**User Acceptance Test:**

Members with names corresponding to the search text become easily viewable after the search. **DONE**

Members with names that do not correspond to the search text disappear after the search. **DONE**

**Definition of Done:**

Have a search bar where users can input a member’s name. **DONE**

Inputting a name in the search bar modifies the list of alumni to only include members with that search term. **DONE**

A button can be pressed to clear the search bar and bring back the entire list of alumni. **DONE**

**Pull request merged**
